# This file was generated by GoReleaser. DO NOT EDIT.
cask "diaspar" do
  version "3.11.3"

  on_macos do
    on_arm do
      sha256 "557426c8ed1fbfb03396461f92a2ad24ada9104c3e059771c661d2037bc174c8"
      url "https://github.com/lavrenlabs/diaspar-releases/releases/download/v#{version}/diaspar_darwin_arm64.tar.gz",
        verified: "github.com/lavrenlabs/diaspar-releases/"
    end
    on_intel do
      sha256 "6b59bcb488703f7e4722f9fe3f4cd12bc686c35f1b25abc9c19f9f261504a8ea"
      url "https://github.com/lavrenlabs/diaspar-releases/releases/download/v#{version}/diaspar_darwin_amd64.tar.gz",
        verified: "github.com/lavrenlabs/diaspar-releases/"
    end
  end
  on_linux do
    on_arm do
      sha256 "29956d55b8c62e2bea62a4e7bacd7335c73b7900c22d06019bfee57c4be0ee7a"
      url "https://github.com/lavrenlabs/diaspar-releases/releases/download/v#{version}/diaspar_linux_arm64.tar.gz",
        verified: "github.com/lavrenlabs/diaspar-releases/"
    end
    on_intel do
      sha256 "109b5b7381f69b351ce1f87c13927709e1b274199f9dbc5a69cf5ec9d7d7354f"
      url "https://github.com/lavrenlabs/diaspar-releases/releases/download/v#{version}/diaspar_linux_amd64.tar.gz",
        verified: "github.com/lavrenlabs/diaspar-releases/"
    end
  end

  name "diaspar"
  desc "Persistent memory system for AI coding agents"
  homepage "https://github.com/lavrenlabs/diaspar-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "diaspar"

  # No zap stanza required
end
