# This file was generated by GoReleaser. DO NOT EDIT.
cask "diaspar" do
  version "3.11.1"

  on_macos do
    on_arm do
      sha256 "c415e08e0c2e9d270c824cd95f8b1ae650790009229a1281f2a7e3a17aff11f9"
      url "https://github.com/lavrenlabs/diaspar-releases/releases/download/v#{version}/diaspar_darwin_arm64.tar.gz",
        verified: "github.com/lavrenlabs/diaspar-releases/"
    end
    on_intel do
      sha256 "be7b032b0eea95dc39105cd45b92b9e80f7ab8a03ddb770526e8661f1785efe5"
      url "https://github.com/lavrenlabs/diaspar-releases/releases/download/v#{version}/diaspar_darwin_amd64.tar.gz",
        verified: "github.com/lavrenlabs/diaspar-releases/"
    end
  end
  on_linux do
    on_arm do
      sha256 "f9d08742c6d1ccc4ae83b2e82e0cfa4ff014ead5ce59d9112310da58d10f800d"
      url "https://github.com/lavrenlabs/diaspar-releases/releases/download/v#{version}/diaspar_linux_arm64.tar.gz",
        verified: "github.com/lavrenlabs/diaspar-releases/"
    end
    on_intel do
      sha256 "42e7c557b480aa87f96f708b380b44fe3993fa997dd8503ec52237fbd7ecaa80"
      url "https://github.com/lavrenlabs/diaspar-releases/releases/download/v#{version}/diaspar_linux_amd64.tar.gz",
        verified: "github.com/lavrenlabs/diaspar-releases/"
    end
  end

  name "diaspar"
  desc "Persistent memory system for AI coding agents"
  homepage "https://github.com/lavrenlabs/diaspar-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "diaspar"

  # No zap stanza required
end
