# This file was generated by GoReleaser. DO NOT EDIT.
cask "diaspar" do
  version "3.3.0"

  on_macos do
    on_intel do
      sha256 "7b019ad4c02dd60a169a3d399d071f6b38f71209d88340c1ca1a1271d886480f"
      url "https://github.com/lavrenlabs/diaspar-releases/releases/download/v#{version}/diaspar_darwin_amd64.tar.gz",
        verified: "github.com/lavrenlabs/diaspar-releases/"
    end
    on_arm do
      sha256 "56291bd1e3f1a93b5fbd159b2642bf807cd6ce7322158219683342653301e83e"
      url "https://github.com/lavrenlabs/diaspar-releases/releases/download/v#{version}/diaspar_darwin_arm64.tar.gz",
        verified: "github.com/lavrenlabs/diaspar-releases/"
    end
  end

  on_linux do
    on_intel do
      sha256 "54013dfeb20ee1fd31a59bbde4409056ebcb3a65b087870934fc44f47370eb39"
      url "https://github.com/lavrenlabs/diaspar-releases/releases/download/v#{version}/diaspar_linux_amd64.tar.gz",
        verified: "github.com/lavrenlabs/diaspar-releases/"
    end
    on_arm do
      sha256 "9efe6278106fde6339612c1446733006ae099b0e5db7e5f23c650664e10de120"
      url "https://github.com/lavrenlabs/diaspar-releases/releases/download/v#{version}/diaspar_linux_arm64.tar.gz",
        verified: "github.com/lavrenlabs/diaspar-releases/"
    end
  end

  name "diaspar"
  desc "Persistent memory system for AI coding agents"
  homepage "https://github.com/lavrenlabs/diaspar-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "diaspar"

  # No zap stanza required

end
