# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemo" do
  version "2.4.1"

  on_macos do
    on_intel do
      sha256 "e2b69fbd014d2a3f8477ba232ecf24b7326c7176e60392cc15dfd6185f756b98"
      url "https://github.com/masterbor/mnemo/releases/download/v#{version}/mnemo_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4593dc316379a52195808b66c08b28f35444308da969e76893d7613dd12bdb51"
      url "https://github.com/masterbor/mnemo/releases/download/v#{version}/mnemo_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a4c6d90d19f96a1459a9133a02c59ee416ccdc9217d24afe0b8ffb948d726bb3"
      url "https://github.com/masterbor/mnemo/releases/download/v#{version}/mnemo_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f2b727efa2b6052ef63e8e0e37b08d8973cbf7a86b1320509b800c6fc6a5f34"
      url "https://github.com/masterbor/mnemo/releases/download/v#{version}/mnemo_linux_arm64.tar.gz"
    end
  end

  name "mnemo"
  desc "Persistent memory system for AI coding agents"
  homepage "https://github.com/masterbor/mnemo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnemo"

  # No zap stanza required

end
