# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemo" do
  version "2.4.0"

  on_macos do
    on_intel do
      sha256 "ee4bbbfbdadab00d0acf409a2a06395142dc59f6657bbb5e57542b32636bfaab"
      url "https://github.com/masterbor/mnemo/releases/download/v#{version}/mnemo_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "33e2dfe76ba8da3c53e3de76db32f25b6fb4594f333e4104c27a8683368d95e4"
      url "https://github.com/masterbor/mnemo/releases/download/v#{version}/mnemo_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9ec8be42e0abf8589c715aa658a47fb7f067297ab5f1af3c5933bcd44adb944c"
      url "https://github.com/masterbor/mnemo/releases/download/v#{version}/mnemo_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9aa658f017a81b9a5b0ce39209348fe1e45629afc89ebcde391d449cf316524d"
      url "https://github.com/masterbor/mnemo/releases/download/v#{version}/mnemo_linux_arm64.tar.gz"
    end
  end

  name "mnemo"
  desc "Persistent memory system for AI coding agents"
  homepage "https://github.com/masterbor/mnemo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnemo"

  # No zap stanza required

end
