# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemo" do
  version "2.3.0"

  on_macos do
    on_intel do
      url "https://github.com/masterbor/mnemo/releases/download/v#{version}/mnemo_#{version}_darwin_amd64.tar.gz"
      sha256 "fbacaa5e476588c0ccead3a26fab4f81620750754ca8c052658ac87d37db6aba"
    end
    on_arm do
      url "https://github.com/masterbor/mnemo/releases/download/v#{version}/mnemo_#{version}_darwin_arm64.tar.gz"
      sha256 "ccab0c0a9b840a40cda67a8fa4c36f3785c900323a2c521e0f918b52d17473ad"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/masterbor/mnemo/releases/download/v#{version}/mnemo_#{version}_linux_amd64.tar.gz"
      sha256 "8820685a53666fc972c5b56121ea0ddd791e787c9f68a17f9927f2de3865d625"
    end
    on_arm do
      url "https://github.com/masterbor/mnemo/releases/download/v#{version}/mnemo_#{version}_linux_arm64.tar.gz"
      sha256 "89ce384ffdd4850046da608e33c82c21fcd8d8273ac0a2b0c63a5a707f9f01de"
    end
  end

  name "mnemo"
  desc "Persistent memory system for AI coding agents"
  homepage "https://github.com/masterbor/mnemo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnemo"

  # No zap stanza required

end
